
services:
  nginx-proxy:
    image: dominikbechstein/nginx-forward-proxy
    environment:
      - TZ=Australia/Perth
    container_name: nginx-forward-proxy
    network_mode: host
    volumes:
      - /opt/proxy/nginx.conf:/usr/local/nginx/conf/nginx.conf:rw
      - /opt/proxy/conf.d:/etc/nginx/conf.d:rw
      - /opt/proxy/ssl:/etc/nginx/ssl:rw
      - /opt/proxy/logs:/var/log/nginx:rw
      - nginx-cache:/var/cache/nginx/
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx-acl-architect:
    image: nginx:alpine
    container_name: nginx-acl-architect
    environment:
      - TZ=Australia/Perth
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - /opt/proxy/nginx.conf:/opt/proxy/nginx.conf:rw
      - /opt/proxy/logs:/var/log/nginx:rw
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - nginx-proxy

volumes:
  nginx-cache:
