
services:
  nginx-proxy:
    image: dominikbechstein/nginx-forward-proxy
    environment:
      - TZ=Australia/Perth
      - NODE_ENV=production
    container_name: nginx-forward-proxy
    network_mode: host  # Use host network
    volumes:
      - /opt/proxy/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - /opt/proxy/conf.d:/etc/nginx/conf.d:rw
      - /opt/proxy/ssl:/etc/nginx/ssl:rw
      - /opt/proxy/logs:/var/log/nginx:rw
      - nginx-cache:/var/cache/nginx/
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx-acl-architect:
    image: node:20-alpine
    container_name: nginx-acl-architect
    environment:
      - TZ=Australia/Perth
      - NODE_ENV=production
      - PORT=3000
    network_mode: host  # Use host network
    volumes:
      - ./:/app:rw
      # Changed to read-write access for the nginx.conf file
      - /opt/proxy/nginx.conf:/app/nginx.conf:rw
      - /opt/proxy/logs:/var/log/nginx:ro
    working_dir: /app
    command: >
      sh -c "npm ci &&
             echo 'Building project...' &&
             node build.js &&
             node server.js"
    restart: always
    depends_on:
      - nginx-proxy

volumes:
  nginx-cache:
