
services:
  nginx-proxy:
    image: dominikbechstein/nginx-forward-proxy
    environment:
      - TZ=Australia/Perth
      - NODE_ENV=production
    container_name: nginx-forward-proxy
    network_mode: host  # Use host network
    volumes:
      - /opt/proxy/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - /opt/proxy/conf.d:/etc/nginx/conf.d:rw
      - /opt/proxy/ssl:/etc/nginx/ssl:rw
      - /opt/proxy/logs:/var/log/nginx:rw
      - nginx-cache:/var/cache/nginx/
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8080:8080"  # Explicitly map the NGINX proxy port

  nginx-acl-architect:
    image: node:20-alpine
    container_name: nginx-acl-architect
    environment:
      - TZ=Australia/Perth
      - NODE_ENV=production
      - PATH=/app/node_modules/.bin:$PATH
    ports:
      - "3000:3000"  # Explicitly map the web UI port
    volumes:
      - ./:/app:rw
      - /opt/proxy/nginx.conf:/app/nginx.conf:rw
      - /opt/proxy/logs:/var/log/nginx:ro
    working_dir: /app
    command: >
      sh -c "npm ci &&
             npm install --save-dev vite @vitejs/plugin-react-swc lovable-tagger &&
             npm run build &&
             npm install -g serve &&
             serve -s dist -l 3000 --no-clipboard"
    restart: always
    depends_on:
      - nginx-proxy

volumes:
  nginx-cache:
